# Generated by Django 5.2.8 on 2025-11-28 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gateway_response', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
