# Generated by Django 5.2.8 on 2025-12-02 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodev', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='details',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='service',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='plan',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='project_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('responded', 'Responded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
