# Generated by Django 5.2.8 on 2025-12-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodev', '0002_remove_quoterequest_details_remove_quoterequest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
