# Generated by Django 5.2.8 on 2025-12-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodev', '0004_remove_invoice_client_remove_invoice_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
