# Generated by Django 5.2.8 on 2026-01-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodev', '0005_quoterequest_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdevService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('items', models.TextField(help_text='Enter bullet points, one per line')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
