# Generated by Django 5.2.8 on 2025-12-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0005_clientmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
