# Generated by Django 5.2.8 on 2026-01-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_booknow_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
