# Generated by Django 5.2.8 on 2026-01-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0007_digitalservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalservices',
            name='item',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
