# Generated by Django 5.2.8 on 2026-01-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0008_digitalservices_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalservices',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='digitalservices',
            name='item',
        ),
        migrations.AddField(
            model_name='digitalservices',
            name='items',
            field=models.TextField(default='Not specified', help_text='Enter one item per line (bullet points)'),
        ),
    ]
