# Generated by Django 5.2.8 on 2026-01-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0009_rename_description_digitalservices_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('date', models.DateField()),
                ('image', models.URLField()),
                ('full_content', models.TextField(help_text='You can use HTML for lists and paragraphs')),
            ],
        ),
    ]
