# Generated by Django 5.2.8 on 2026-01-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0010_digitalblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='team/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
