# Generated by Django 5.2.8 on 2026-02-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0017_rename_end_time_booking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
