# Generated by Django 5.2.8 on 2026-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0018_clientpayment_quantity_clientpayment_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpayment',
            name='service_name',
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
