# Generated by Django 5.2.8 on 2026-02-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0019_remove_clientpayment_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
