# Generated by Django 5.2.8 on 2026-02-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0020_clientprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
