# Generated by Django 5.2.8 on 2026-02-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0021_clientprofile_first_name_clientprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
