# Generated by Django 5.2.8 on 2026-02-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0022_digitalprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalprofile',
            name='country',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('USA', 'USA'), ('UK', 'UK'), ('Other', 'Other')], default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='digitalprofile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French')], default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='digitalprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=50),
        ),
    ]
