# Generated by Django 5.2.8 on 2025-12-17 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_hub', '0003_rename_payment_payments_alter_payments_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='therapy_hub.booking'),
        ),
    ]
