# Generated by Django 5.2.8 on 2025-12-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_hub', '0004_payments_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, choices=[('individual_therapy', 'Individual Therapy'), ('couples_therapy', 'Couples Therapy'), ('corporate_therapy', 'Corporate Therapy'), ('basic_plan', 'Basic Plan'), ('standard_plan', 'Standard Plan'), ('premium_plan', 'Premium Plan')], max_length=100),
        ),
    ]
