# Generated by Django 5.2.8 on 2025-12-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_hub', '0006_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team_therapy/'),
        ),
    ]
