# Generated by Django 5.2.8 on 2025-12-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_hub', '0008_therapyservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapyservice',
            name='slug',
        ),
    ]
