# Generated by Django 5.2.8 on 2025-12-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_hub', '0009_remove_therapyservice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('client_profile', models.TextField()),
                ('challenge', models.TextField()),
                ('approach', models.TextField(help_text='Use bullet points separated by new lines')),
                ('outcome', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
