# Generated by Django 5.2.8 on 2025-12-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_hub', '0010_casestudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField(help_text='Paste image URL from Unsplash or elsewhere')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('button_text', models.CharField(default='Register Now', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
